In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return(np.exp(x)/(1+np.exp(x)))

def forward0(x, w, b):
    v=w*x+b
    return(sigmoid(v))

In [3]:
def forward(x, l):
    w_list = []
    b_list = []

    x = np.matrix(x).T

    for i, j in enumerate(l):
        if i:
            w = np.ones((j, l[i-1]))
        else:
            w = np.ones((j, x.shape[0]))
        w_list.append(w)

        b = np.ones(j)
        b_list.append(b)

        x = forward0(x, np.matrix(w), np.matrix(b).T)
        print(x)

    y = x[0, 0]
    return(y)

In [4]:
x = np.array([1, 2, 3])
l = [3, 4, 1]
forward(x, l)

[[0.99908895]
 [0.99908895]
 [0.99908895]]
[[0.98196545]
 [0.98196545]
 [0.98196545]
 [0.98196545]]
[[0.9928101]]


0.9928100975896637

In [110]:
def backwards0(x, wa, gradientWb, eta, gradientAF, i):
    gradientWb = np.matrix(gradientWb).T
    x = np.matrix(x)
    gradientWa = gradientWb*x
    wa = wa-eta*gradientWa
    return([wa, gradientWa])

In [ ]:
def backwards0(gradientYL, x, y, w, i):
    jacobianVY = y*(1-y)
    gradientVL = jacobianVY * gradientYL
    gradientUL = gradientVL
    gradientXL = w.T * gradientUL
    gradientWiL = gradientUL[i]*x
    gradientBL = gradientVL
    return([gradientXL, gradientWiL, gradientBL])

In [111]:
gradientLoss = np.random.rand(3)
x = np.random.rand(4)
w = np.random.rand(3,4)
eta = 0.1

In [112]:
backwards0(x, w, gradientLoss, eta)

matrix([[0.3367525 , 0.01942241, 0.0807967 , 0.91248731],
        [0.53912076, 0.27358483, 0.91363997, 0.29526991],
        [0.24230199, 0.84306464, 0.09336134, 0.75670972]])