In [1]:
import numpy as np

In [15]:
import NeuralNetwork as nn

In [6]:
def trainNetwork(x, y, l):
    net = nn.forward(x, l)
    gradientYL = 2*(y - net[0][len(l)])
    for ll in range(len(l)-1,-1,-1):
        x0 = net[0][ll]
        y_hat = net[0][ll+1]
        w=net[1][ll]
        L = nn.backwards0(gradientYL, x0, y_hat, w)
        gradientYL = L[0]

In [7]:
x = np.array([1, 2, 3])
y=1.5
l = [3, 4, 1]
trainNetwork(x, y, l)

In [9]:
x = np.array([1, 2, 3])
y=1.5
l = [3, 4, 1]
net = nn.forward(x, l)
net

[[matrix([[1],
          [2],
          [3]]),
  matrix([[0.99908895],
          [0.99908895],
          [0.99908895]]),
  matrix([[0.98196545],
          [0.98196545],
          [0.98196545],
          [0.98196545]]),
  matrix([[0.9928101]])],
 [matrix([[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]),
  matrix([[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]),
  matrix([[1., 1., 1., 1.]])],
 [matrix([[1., 1., 1.]]), matrix([[1., 1., 1., 1.]]), matrix([[1.]])]]

In [18]:
gradientYL = 2*(y - net[0][len(l)])
for ll in range(len(l)-1,-1,-1):
    x0 = net[0][ll]
    y_hat = net[0][ll+1]
    w=net[1][ll]
    L = nn.backwards0(gradientYL, x0, y_hat, w)
    gradientYL = L[0]

In [19]:
nn.backwards1(y, net, l, 0.5)

AttributeError: module 'NeuralNetwork' has no attribute 'backwards1'