In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return(np.exp(x)/(1+np.exp(x)))

def forward0(x, w, b):
    v=w*x+b
    return(sigmoid(v))

In [31]:
def forward(x, l):
    w_list = []
    b_list = []
    y_list = []

    x = np.matrix(x).T

    for i, j in enumerate(l):
        if i:
            w = np.ones((j, l[i-1]))
        else:
            w = np.ones((j, x.shape[0]))
        w_list.append(np.matrix(w))

        b = np.ones(j)
        b_list.append(np.matrix(b))

        x = forward0(x, np.matrix(w), np.matrix(b).T)
        y_list.append(x)

    #y = x[0, 0]
    return([y_list, w_list, b_list])

In [32]:
x = np.array([1, 2, 3])
l = [3, 4, 1]
net = forward(x, l)
net

[[matrix([[0.99908895],
          [0.99908895],
          [0.99908895]]),
  matrix([[0.98196545],
          [0.98196545],
          [0.98196545],
          [0.98196545]]),
  matrix([[0.9928101]])],
 [matrix([[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]),
  matrix([[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]),
  matrix([[1., 1., 1., 1.]])],
 [matrix([[1., 1., 1.]]), matrix([[1., 1., 1., 1.]]), matrix([[1.]])]]

In [50]:
def backwards0(gradientYL, x, y, w, i):
    jacobianVY = y*(1-y)
    gradientVL = np.multiply(jacobianVY,gradientYL)
    gradientUL = gradientVL
    gradientXL = w.T * gradientUL
    gradientWiL = gradientUL[i,0]*x
    gradientBL = gradientVL
    return([gradientXL, gradientWiL, gradientBL])

In [48]:
jacobianVY = y*(1-y)
jacobianVY

-0.75

In [49]:
gradientVL = np.multiply(jacobianVY,gradientYL)
gradientVL

matrix([[-0.76078485]])

In [44]:
y = 1.5
y

1.5

In [11]:
net[0] #output

matrix([[0.9928101]])

In [12]:
net[1] #weight

array([[1., 1., 1., 1.]])

In [13]:
net[2] #threshold

array([1.])

In [36]:
gradientYL = 2*(y - net[0][2])
gradientYL

matrix([[1.0143798]])

In [37]:
x = net[0][1]
x

matrix([[0.98196545],
        [0.98196545],
        [0.98196545],
        [0.98196545]])

In [38]:
y_hat = net[0][2]
y_hat

matrix([[0.9928101]])

In [39]:
w=net[1][2]
w

matrix([[1., 1., 1., 1.]])

In [40]:
i = 0

In [51]:
backwards0(gradientYL, x, y_hat, w, i)

[matrix([[0.00724085],
         [0.00724085],
         [0.00724085],
         [0.00724085]]),
 matrix([[0.00711027],
         [0.00711027],
         [0.00711027],
         [0.00711027]]),
 matrix([[0.00724085]])]

In [ ]:
backwards0(gradientYL, x, y_hat, w, i)