In [1]:
import numpy as np
import NeuralNetwork as nn

In [2]:
x = np.array([1, 2, 3])
y=1.5
l = [3, 4, 1]
nn.trainNet(x, y, l)

[[matrix([[0.9999975, 0.999995 , 0.9999925],
          [0.9999975, 0.999995 , 0.9999925],
          [0.9999975, 0.999995 , 0.9999925]]),
  matrix([[0.99931416, 0.99931416, 0.99931416],
          [0.99931416, 0.99931416, 0.99931416],
          [0.99931416, 0.99931416, 0.99931416],
          [0.99931416, 0.99931416, 0.99931416]]),
  matrix([[0.96130849, 0.96130849, 0.96130849, 0.96130849]])],
 [matrix([[0.9999975],
          [0.9999975],
          [0.9999975]]),
  matrix([[0.99931353],
          [0.99931353],
          [0.99931353],
          [0.99931353]]),
  matrix([[0.96059701]])]]